"""initial complete schema

Revision ID: 4f3c55cfee7d
Revises:
Create Date: 2026-07-25 20:54:59.331814

THE COMPLETE FINAL SCHEMA, IN ONE REVISION.

The database was throwaway when the refactor started, so instead of a baseline
stamp plus a chain of ALTERs there is exactly one migration containing 17
tables: the 7 that existed (users, doctor_profiles, ai_scans,
doctor_availability, doctor_fees, appointments, doctor_ratings -- every column,
index, FK and cascade preserved byte-for-byte) plus 10 new ones.

New tables
    refresh_tokens              rotating opaque sessions, sha256-at-rest
    audit_logs                  act-as delegation + privileged actions
    email_otps                  purpose-scoped OTPs (signup/reset/email_change)
    consent_documents           versioned consent text
    user_consents               append-only grant log, incl. per-object
                                consents via target_ref ('scan:1234')
    appointment_requests        "find me a doctor" fan-out
    appointment_request_doctors candidate doctors + their accept/decline
    appointment_request_slots   patient's preferred times
    scan_attachments            extra photos per scan
    image_access_log            who viewed which medical image, when

New columns on existing tables
    users        is_root, is_active, token_version, last_login_at,
                 last_login_ip, marketing_opt_in, pending_email
    ai_scans     patient_notes, is_sensitive, sensitivity_reason, blur_url,
                 thumb_url, image_deleted_at, image_deleted_by,
                 image_delete_reason, image_delete_consent_at, image_purged_at
    appointments request_id, rebooked_from_id, slot_start

New constraints worth knowing about
    ck_doctor_ratings_rating_range   rating BETWEEN 1 AND 5
    uq_rating_appt / uq_rating_scan  partial uniques that make the
                                     /api/rate-doctor upsert race-proof
    uq_appt_doctor_slot              partial unique on
                                     (doctor_id, slot_start) WHERE status IN
                                     ('Scheduled','Pending-Conflict') -- kills
                                     the double-booking race. Partial on
                                     slot_start IS NOT NULL, so legacy
                                     free-text rows are simply not covered.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f3c55cfee7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_url', sa.String(length=300), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_type', 'version', name='uq_consent_type_version')
    )
    op.create_index(op.f('ix_consent_documents_consent_type'), 'consent_documents', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consent_documents_id'), 'consent_documents', ['id'], unique=False)
    op.create_index(op.f('ix_consent_documents_is_current'), 'consent_documents', ['is_current'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('otp_created_at', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('pending_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_root'), 'users', ['is_root'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('ai_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('prediction_result', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('doctor_comment', sa.Text(), nullable=True),
    sa.Column('invite_to_clinic', sa.Boolean(), nullable=True),
    sa.Column('patient_questionnaire', sa.Text(), nullable=True),
    sa.Column('severity_level', sa.String(length=50), nullable=True),
    sa.Column('triage_score', sa.Integer(), nullable=True),
    sa.Column('triage_reasons', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.Integer(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('doctor_email', sa.String(length=255), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('patient_notes', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('sensitivity_reason', sa.String(length=50), nullable=True),
    sa.Column('blur_url', sa.String(length=500), nullable=True),
    sa.Column('thumb_url', sa.String(length=500), nullable=True),
    sa.Column('image_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('image_deleted_by', sa.Integer(), nullable=True),
    sa.Column('image_delete_reason', sa.String(length=255), nullable=True),
    sa.Column('image_delete_consent_at', sa.DateTime(), nullable=True),
    sa.Column('image_purged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_scans_created_at'), 'ai_scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_scans_doctor_id'), 'ai_scans', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_ai_scans_id'), 'ai_scans', ['id'], unique=False)
    op.create_index(op.f('ix_ai_scans_is_sensitive'), 'ai_scans', ['is_sensitive'], unique=False)
    op.create_index(op.f('ix_ai_scans_prediction_result'), 'ai_scans', ['prediction_result'], unique=False)
    op.create_index(op.f('ix_ai_scans_review_status'), 'ai_scans', ['review_status'], unique=False)
    op.create_index(op.f('ix_ai_scans_severity_level'), 'ai_scans', ['severity_level'], unique=False)
    op.create_index(op.f('ix_ai_scans_status'), 'ai_scans', ['status'], unique=False)
    op.create_index(op.f('ix_ai_scans_triage_score'), 'ai_scans', ['triage_score'], unique=False)
    op.create_index(op.f('ix_ai_scans_user_id'), 'ai_scans', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('subject_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('doctor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('is_off', sa.Boolean(), nullable=True),
    sa.Column('break_start_time', sa.String(length=20), nullable=True),
    sa.Column('break_end_time', sa.String(length=20), nullable=True),
    sa.Column('break_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_availability_day'), 'doctor_availability', ['day'], unique=False)
    op.create_index(op.f('ix_doctor_availability_doctor_id'), 'doctor_availability', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_availability_id'), 'doctor_availability', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_availability_is_off'), 'doctor_availability', ['is_off'], unique=False)
    op.create_table('doctor_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('pkr', sa.Float(), nullable=True),
    sa.Column('usd', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.Column('buffer_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_fees_doctor_id'), 'doctor_fees', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_doctor_fees_id'), 'doctor_fees', ['id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('hospital', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_profiles_city'), 'doctor_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_id'), 'doctor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_license'), 'doctor_profiles', ['license'], unique=True)
    op.create_index(op.f('ix_doctor_profiles_specialty'), 'doctor_profiles', ['specialty'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_doctor_profiles_verification_status'), 'doctor_profiles', ['verification_status'], unique=False)
    op.create_table('email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.CheckConstraint("purpose IN ('signup','reset','email_change')", name='ck_email_otps_purpose'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_id'), 'email_otps', ['id'], unique=False)
    op.create_index(op.f('ix_email_otps_purpose'), 'email_otps', ['purpose'], unique=False)
    op.create_index(op.f('ix_email_otps_user_id'), 'email_otps', ['user_id'], unique=False)
    op.create_index('ix_email_otps_user_purpose', 'email_otps', ['user_id', 'purpose'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('target_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_consent_type'), 'user_consents', ['consent_type'], unique=False)
    op.create_index(op.f('ix_user_consents_id'), 'user_consents', ['id'], unique=False)
    op.create_index(op.f('ix_user_consents_target_ref'), 'user_consents', ['target_ref'], unique=False)
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_index('ix_user_consents_user_type', 'user_consents', ['user_id', 'consent_type'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.String(length=50), nullable=False),
    sa.Column('appointment_time', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('hidden_from_doctor', sa.Boolean(), nullable=True),
    sa.Column('conflict_with_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('rebooked_from_id', sa.Integer(), nullable=True),
    sa.Column('slot_start', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conflict_with_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rebooked_from_id'], ['appointments.id'], ondelete='SET NULL'),
    # NOTE: appointments.request_id -> appointment_requests.id is NOT declared
    # here. appointment_requests is created further down and itself points back
    # at appointments (matched_appointment_id), so the two tables form an FK
    # cycle. The constraint is added as an explicit ALTER at the end of
    # upgrade() -- see "CIRCULAR FOREIGN KEY" below. Autogenerate emits it
    # inline with use_alter=True, which op.create_table silently DROPS; if you
    # regenerate this migration, re-apply this same fix.
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['ai_scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_conflict_with_id'), 'appointments', ['conflict_with_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_hidden_from_doctor'), 'appointments', ['hidden_from_doctor'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_request_id'), 'appointments', ['request_id'], unique=False)
    op.create_index(op.f('ix_appointments_scan_id'), 'appointments', ['scan_id'], unique=False)
    op.create_index(op.f('ix_appointments_slot_start'), 'appointments', ['slot_start'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('uq_appt_doctor_slot', 'appointments', ['doctor_id', 'slot_start'], unique=True, postgresql_where=sa.text("status IN ('Scheduled','Pending-Conflict') AND slot_start IS NOT NULL"))
    op.create_table('scan_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumb_url', sa.String(length=500), nullable=True),
    sa.Column('blur_url', sa.String(length=500), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('image_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['ai_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_attachments_id'), 'scan_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_scan_attachments_scan_id'), 'scan_attachments', ['scan_id'], unique=False)
    op.create_table('appointment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('express', sa.Boolean(), nullable=False),
    sa.Column('patient_note', sa.Text(), nullable=True),
    sa.Column('severity_snapshot', sa.String(length=20), nullable=True),
    sa.Column('triage_score', sa.Integer(), nullable=False),
    sa.Column('triage_reasons', sa.Text(), nullable=True),
    sa.Column('consent_share_scan', sa.Boolean(), nullable=False),
    sa.Column('matched_appointment_id', sa.Integer(), nullable=True),
    sa.Column('matched_doctor_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Open','Matched','Withdrawn','Expired','Declined')", name='ck_appointment_requests_status'),
    sa.ForeignKeyConstraint(['matched_appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['ai_scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_requests_created_at'), 'appointment_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointment_requests_expires_at'), 'appointment_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_appointment_requests_id'), 'appointment_requests', ['id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_patient_id'), 'appointment_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_scan_id'), 'appointment_requests', ['scan_id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_status'), 'appointment_requests', ['status'], unique=False)
    op.create_table('doctor_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_doctor_ratings_rating_range'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['ai_scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_ratings_appointment_id'), 'doctor_ratings', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_created_at'), 'doctor_ratings', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_doctor_id'), 'doctor_ratings', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_id'), 'doctor_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_patient_id'), 'doctor_ratings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_rating'), 'doctor_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_scan_id'), 'doctor_ratings', ['scan_id'], unique=False)
    op.create_index('uq_rating_appt', 'doctor_ratings', ['patient_id', 'appointment_id'], unique=True, postgresql_where=sa.text('appointment_id IS NOT NULL'))
    op.create_index('uq_rating_scan', 'doctor_ratings', ['patient_id', 'scan_id'], unique=True, postgresql_where=sa.text('scan_id IS NOT NULL'))
    op.create_table('image_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('viewer_role', sa.String(length=20), nullable=True),
    sa.Column('variant', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['scan_attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['ai_scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_access_log_id'), 'image_access_log', ['id'], unique=False)
    op.create_index(op.f('ix_image_access_log_scan_id'), 'image_access_log', ['scan_id'], unique=False)
    op.create_index(op.f('ix_image_access_log_viewed_at'), 'image_access_log', ['viewed_at'], unique=False)
    op.create_table('appointment_request_doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=False),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("response IN ('Pending','Accepted','Declined','Withdrawn')", name='ck_request_doctor_response'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['appointment_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'doctor_id', name='uq_request_doctor')
    )
    op.create_index(op.f('ix_appointment_request_doctors_doctor_id'), 'appointment_request_doctors', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_request_doctors_id'), 'appointment_request_doctors', ['id'], unique=False)
    op.create_index(op.f('ix_appointment_request_doctors_request_id'), 'appointment_request_doctors', ['request_id'], unique=False)
    op.create_table('appointment_request_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('slot_date', sa.String(length=20), nullable=True),
    sa.Column('slot_time', sa.String(length=20), nullable=True),
    sa.Column('slot_start', sa.DateTime(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['appointment_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_request_slots_id'), 'appointment_request_slots', ['id'], unique=False)
    op.create_index(op.f('ix_appointment_request_slots_request_id'), 'appointment_request_slots', ['request_id'], unique=False)
    op.create_index(op.f('ix_appointment_request_slots_slot_start'), 'appointment_request_slots', ['slot_start'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # CIRCULAR FOREIGN KEY
    # ------------------------------------------------------------------
    # appointments.request_id -> appointment_requests.id  and
    # appointment_requests.matched_appointment_id -> appointments.id
    # point at each other, so neither table can carry both constraints at
    # CREATE time. appointment_requests holds its side inline (appointments
    # already exists by then); the appointments side is added here, once both
    # tables are present.
    op.create_foreign_key(
        'fk_appointments_request_id',
        'appointments', 'appointment_requests',
        ['request_id'], ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    # Break the FK cycle first, otherwise the drops below deadlock on ordering.
    op.drop_constraint('fk_appointments_request_id', 'appointments', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_request_slots_slot_start'), table_name='appointment_request_slots')
    op.drop_index(op.f('ix_appointment_request_slots_request_id'), table_name='appointment_request_slots')
    op.drop_index(op.f('ix_appointment_request_slots_id'), table_name='appointment_request_slots')
    op.drop_table('appointment_request_slots')
    op.drop_index(op.f('ix_appointment_request_doctors_request_id'), table_name='appointment_request_doctors')
    op.drop_index(op.f('ix_appointment_request_doctors_id'), table_name='appointment_request_doctors')
    op.drop_index(op.f('ix_appointment_request_doctors_doctor_id'), table_name='appointment_request_doctors')
    op.drop_table('appointment_request_doctors')
    op.drop_index(op.f('ix_image_access_log_viewed_at'), table_name='image_access_log')
    op.drop_index(op.f('ix_image_access_log_scan_id'), table_name='image_access_log')
    op.drop_index(op.f('ix_image_access_log_id'), table_name='image_access_log')
    op.drop_table('image_access_log')
    op.drop_index('uq_rating_scan', table_name='doctor_ratings', postgresql_where=sa.text('scan_id IS NOT NULL'))
    op.drop_index('uq_rating_appt', table_name='doctor_ratings', postgresql_where=sa.text('appointment_id IS NOT NULL'))
    op.drop_index(op.f('ix_doctor_ratings_scan_id'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_rating'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_patient_id'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_id'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_doctor_id'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_created_at'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_appointment_id'), table_name='doctor_ratings')
    op.drop_table('doctor_ratings')
    op.drop_index(op.f('ix_appointment_requests_status'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_scan_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_patient_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_expires_at'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_created_at'), table_name='appointment_requests')
    op.drop_table('appointment_requests')
    op.drop_index(op.f('ix_scan_attachments_scan_id'), table_name='scan_attachments')
    op.drop_index(op.f('ix_scan_attachments_id'), table_name='scan_attachments')
    op.drop_table('scan_attachments')
    op.drop_index('uq_appt_doctor_slot', table_name='appointments', postgresql_where=sa.text("status IN ('Scheduled','Pending-Conflict') AND slot_start IS NOT NULL"))
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_slot_start'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scan_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_request_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_hidden_from_doctor'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_conflict_with_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_user_consents_user_type', table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_target_ref'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_consent_type'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_email_otps_user_purpose', table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_user_id'), table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_purpose'), table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_id'), table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_index(op.f('ix_doctor_profiles_verification_status'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_specialty'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_license'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_city'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_doctor_fees_id'), table_name='doctor_fees')
    op.drop_index(op.f('ix_doctor_fees_doctor_id'), table_name='doctor_fees')
    op.drop_table('doctor_fees')
    op.drop_index(op.f('ix_doctor_availability_is_off'), table_name='doctor_availability')
    op.drop_index(op.f('ix_doctor_availability_id'), table_name='doctor_availability')
    op.drop_index(op.f('ix_doctor_availability_doctor_id'), table_name='doctor_availability')
    op.drop_index(op.f('ix_doctor_availability_day'), table_name='doctor_availability')
    op.drop_table('doctor_availability')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_scans_user_id'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_triage_score'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_status'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_severity_level'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_review_status'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_prediction_result'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_is_sensitive'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_id'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_doctor_id'), table_name='ai_scans')
    op.drop_index(op.f('ix_ai_scans_created_at'), table_name='ai_scans')
    op.drop_table('ai_scans')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_root'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_consent_documents_is_current'), table_name='consent_documents')
    op.drop_index(op.f('ix_consent_documents_id'), table_name='consent_documents')
    op.drop_index(op.f('ix_consent_documents_consent_type'), table_name='consent_documents')
    op.drop_table('consent_documents')
    # ### end Alembic commands ###
